mwlib: 
  build: ./mwlib/
  ports: 
    - "8899:8001"
parsoid: 
  build: ./parsoid/
  links: 
    - web
  ports: 
    - "8000:8000"
pgdb: 
  environment: 
    - 
      POSTGRES_PASSWORD: welcome@123
  image: "postgres:latest"
web: 
  build: "."
  links: 
    - pgdb
    - parsoid
    - mwlib
  ports: 
    - "80:80"
  volumes: 
    - "/home/root/resources:/var/www/html/resources"